# Generated by Django 5.2.4 on 2025-07-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(blank=True, max_length=65, null=True, unique=True),
        ),
    ]
